# ==========================================
# STAGE 1: Dependencies
# ==========================================
FROM node:20-alpine AS deps
WORKDIR /app

# Install native dependencies required for Snowflake SDK
RUN apk add --no-cache libc6-compat python3 make g++

COPY package.json package-lock.json ./
RUN npm ci

# ==========================================
# STAGE 2: Builder
# ==========================================
FROM node:20-alpine AS builder
WORKDIR /app

# Copy node_modules and all source code
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Enforce Production Build
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Build application (generates the optimized standalone / server.js)
RUN npm run build

# ==========================================
# STAGE 3: Production Runner
# ==========================================
FROM node:20-alpine AS runner
WORKDIR /app

# Ensure required minimal Snowflake dependencies are present
RUN apk add --no-cache libc6-compat

# Set Runtime Environments
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Secure container by creating a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy essential public assets
COPY --from=builder /app/public ./public

# Set directory ownership
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy Only the standalone server and static assets generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Run as non-root user
USER nextjs

EXPOSE 3000

# Next.js standalone output automatically creates server.js
CMD ["node", "server.js"]
