-- =====================================================
-- Custom SQL Query Audit Table
-- =====================================================
-- Purpose: Immutable-ish operational audit for governed Custom SQL workbench
-- Scope: DATA_QUALITY_DB.DB_METRICS
-- =====================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE DATA_QUALITY_DB;
CREATE SCHEMA IF NOT EXISTS DB_METRICS;
USE SCHEMA DB_METRICS;

CREATE TABLE IF NOT EXISTS DQ_QUERY_AUDIT (
    AUDIT_ID VARCHAR(64) PRIMARY KEY,
    DATASET_ID VARCHAR(255) NOT NULL,
    DATABASE_NAME VARCHAR(255) NOT NULL,
    SCHEMA_NAME VARCHAR(255) NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    EXECUTED_BY VARCHAR(255),
    EXECUTED_ROLE VARCHAR(255),
    WAREHOUSE_USED VARCHAR(255),
    RAW_SQL STRING,
    COMPILED_SQL STRING,
    COMMAND_TYPE VARCHAR(50),
    IS_ADMIN_EXECUTION BOOLEAN DEFAULT FALSE,
    IS_BLOCKED BOOLEAN DEFAULT FALSE,
    STATUS VARCHAR(20) NOT NULL,
    QUERY_ID VARCHAR(255),
    ROWS_RETURNED NUMBER,
    ROWS_UPDATED NUMBER,
    EXECUTION_TIME_MS NUMBER,
    ERROR_CODE VARCHAR(100),
    ERROR_MESSAGE STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Audit trail for governed dataset-level Custom SQL executions';

ALTER TABLE DQ_QUERY_AUDIT CLUSTER BY (CREATED_AT, DATASET_ID, TABLE_NAME);

COMMENT ON COLUMN DQ_QUERY_AUDIT.DATASET_ID IS 'Dataset route identifier used by platform';
COMMENT ON COLUMN DQ_QUERY_AUDIT.COMPILED_SQL IS 'SQL executed after placeholder substitution and guardrails';
COMMENT ON COLUMN DQ_QUERY_AUDIT.IS_BLOCKED IS 'True when request was blocked before execution';
COMMENT ON COLUMN DQ_QUERY_AUDIT.QUERY_ID IS 'Snowflake query id for executed statements';




-- Create roles
CREATE ROLE ADMIN_ROLE;
CREATE ROLE DATA_ENGINEER_ROLE;
CREATE ROLE ANALYST_ROLE;
CREATE ROLE VIEWER_ROLE;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE TESTING TO ROLE ADMIN_ROLE;
GRANT USAGE ON DATABASE TESTING TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE TESTING TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE TESTING TO ROLE VIEWER_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA TESTING.TESTING_SCHEMA TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TESTING.TESTING_SCHEMA TO ROLE VIEWER_ROLE;

--Createing Users
CREATE user Dipak;
CREATE user Mayuri;
CREATE user Om;
CREATE user Renuka;
-- Assign users
GRANT ROLE ADMIN_ROLE TO USER Dipak;
GRANT ROLE DATA_ENGINEER_ROLE TO USER Mayuri;
GRANT ROLE ANALYST_ROLE TO USER Om;
GRANT ROLE VIEWER_ROLE TO USER Renuka;


