-- ============================================================================
-- PI_QLENS RBAC + KEY PAIR AUTHENTICATION SETUP (INFRASTRUCTURE ONLY)
-- Pi-Qualytics / PI_QLens
-- ============================================================================
-- Purpose:
-- 1) Ensure PI_QLens RBAC roles/hierarchy/grants exist
-- 2) Ensure service user PIQLENS_APP_USER exists
-- 3) Attach RSA public key to service user
-- 4) Validate key registration and RBAC access
--
-- IMPORTANT:
-- - Keep existing password auth active during migration.
-- - This script is infrastructure-only; no application code changes.
-- - Run as SECURITYADMIN or ACCOUNTADMIN.
-- ============================================================================

USE ROLE SECURITYADMIN;
USE DATABASE DATA_QUALITY_DB;

-- ============================================================================
-- SECTION 1: ROLE CREATION & HIERARCHY
-- ============================================================================

CREATE ROLE IF NOT EXISTS PIQLENS_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS PIQLENS_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS PIQLENS_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS PIQLENS_VIEWER_ROLE;

GRANT ROLE PIQLENS_VIEWER_ROLE TO ROLE PIQLENS_ANALYST_ROLE;
GRANT ROLE PIQLENS_ANALYST_ROLE TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT ROLE PIQLENS_ENGINEER_ROLE TO ROLE PIQLENS_ADMIN_ROLE;

-- ============================================================================
-- SECTION 2: DATABASE, SCHEMA, TABLE, AND WAREHOUSE GRANTS
-- ============================================================================

-- Database access
GRANT USAGE ON DATABASE DATA_QUALITY_DB TO ROLE PIQLENS_VIEWER_ROLE;

-- Schema access
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.DATA_CATALOG TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.DB_METRICS TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.DQ_CONFIG TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.DQ_METRICS TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.DQ_ENGINE TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON SCHEMA DATA_QUALITY_DB.PUBLIC TO ROLE PIQLENS_VIEWER_ROLE;

-- Viewer table permissions
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DQ_METRICS TO ROLE PIQLENS_VIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DB_METRICS TO ROLE PIQLENS_VIEWER_ROLE;

-- Analyst permissions
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DQ_CONFIG TO ROLE PIQLENS_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DATA_CATALOG TO ROLE PIQLENS_ANALYST_ROLE;

-- Engineer permissions
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DQ_CONFIG TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DQ_METRICS TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DB_METRICS TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DQ_ENGINE TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA DATA_QUALITY_DB.DATA_CATALOG TO ROLE PIQLENS_ENGINEER_ROLE;

-- Admin permissions
GRANT ALL PRIVILEGES ON DATABASE DATA_QUALITY_DB TO ROLE PIQLENS_ADMIN_ROLE;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DQ_METRICS TO ROLE PIQLENS_VIEWER_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DQ_METRICS TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DB_METRICS TO ROLE PIQLENS_VIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DQ_CONFIG TO ROLE PIQLENS_ANALYST_ROLE;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DQ_CONFIG TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DB_METRICS TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA DATA_QUALITY_DB.DQ_ENGINE TO ROLE PIQLENS_ENGINEER_ROLE;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE DQ_ANALYTICS_WH TO ROLE PIQLENS_VIEWER_ROLE;
GRANT USAGE ON WAREHOUSE DQ_ANALYTICS_WH TO ROLE PIQLENS_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DQ_ANALYTICS_WH TO ROLE PIQLENS_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE DQ_ANALYTICS_WH TO ROLE PIQLENS_ADMIN_ROLE;

-- ============================================================================
-- SECTION 3: SERVICE USER SETUP
-- ============================================================================

CREATE USER IF NOT EXISTS PIQLENS_APP_USER
  DEFAULT_ROLE = PIQLENS_ENGINEER_ROLE
  DEFAULT_WAREHOUSE = DQ_ANALYTICS_WH
  DEFAULT_NAMESPACE = DATA_QUALITY_DB.DQ_ENGINE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE PIQLENS_ENGINEER_ROLE TO USER PIQLENS_APP_USER;

-- ============================================================================
-- SECTION 4: KEY PAIR ATTACHMENT
-- ============================================================================

-- Replace <<PASTE_PUBLIC_KEY_WITHOUT_HEADERS>> with your key body only.
-- Example source: keys/piqlens_public_key_body.txt
ALTER USER PIQLENS_APP_USER
  SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxlRWpsHfpwikaGvldPe4LB/WGxAHczMGgHr4xElVNGYui6JZGdF2RCIy86wOvc+cHKUSDw2viZaBaOZJBVnAi7RkclxMQ+WeA9NxWflESFOtSze8ueRN59JyM+8Z7B/uqEw68U4BTUiOZAgBmkK//QToUlpWI9eOa53eRjZh1EaE+VXxC23+TRg9CmaOcx3eaCpJnSA/ytbepI6egWrVg7oFmu754z59PkVKibdl054abnVarScYHigC8qKFPOKbTXNSeOd7Udzf0Jx1h/7LZ6bmmfZNyTsSkdriGcx4CIZLInhSpjzbmuPZR4Uoj7zRL/nJ4a9UbU4s1y3ZKtKz4QIDAQAB
';

-- Verify key is attached
DESC USER PIQLENS_APP_USER;

SHOW PARAMETERS LIKE 'RSA_PUBLIC_KEY' FOR USER PIQLENS_APP_USER;
SHOW PARAMETERS LIKE 'RSA_PUBLIC_KEY_FP' FOR USER PIQLENS_APP_USER;

-- ============================================================================
-- SECTION 5: RBAC INTEGRITY VALIDATION (READ-ONLY CHECKS)
-- ============================================================================

-- Verify user defaults
SHOW USERS LIKE 'PIQLENS_APP_USER';

-- Verify role inheritance and user grants
SHOW GRANTS OF ROLE PIQLENS_VIEWER_ROLE;
SHOW GRANTS OF ROLE PIQLENS_ANALYST_ROLE;
SHOW GRANTS OF ROLE PIQLENS_ENGINEER_ROLE;
SHOW GRANTS OF ROLE PIQLENS_ADMIN_ROLE;
SHOW GRANTS TO USER PIQLENS_APP_USER;

-- Runtime access validation should be run in a session authenticated as
-- PIQLENS_APP_USER (or any user assigned PIQLENS_ENGINEER_ROLE).
-- If your worksheet user is not assigned PIQLENS_ENGINEER_ROLE,
-- USE ROLE PIQLENS_ENGINEER_ROLE will fail by design.
--
-- USE ROLE PIQLENS_ENGINEER_ROLE;
-- USE WAREHOUSE DQ_ANALYTICS_WH;
-- USE DATABASE DATA_QUALITY_DB;
--
-- USE SCHEMA DATA_CATALOG;
-- SELECT CURRENT_USER() AS USER_NAME,
--        CURRENT_ROLE() AS ACTIVE_ROLE,
--        CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE,
--        CURRENT_DATABASE() AS ACTIVE_DATABASE,
--        CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
--
-- USE SCHEMA DB_METRICS;
-- SELECT CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
--
-- USE SCHEMA DQ_CONFIG;
-- SELECT CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
--
-- USE SCHEMA DQ_ENGINE;
-- SELECT CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
--
-- USE SCHEMA DQ_METRICS;
-- SELECT CURRENT_SCHEMA() AS ACTIVE_SCHEMA;

-- ============================================================================
-- End of script
-- ============================================================================




