USE ROLE SECURITYADMIN;






USE ROLE ACCOUNTADMIN;

-- Optional cleanup to avoid stale state
ALTER USER PIQLENS_APP_USER UNSET RSA_PUBLIC_KEY;
ALTER USER PIQLENS_APP_USER UNSET RSA_PUBLIC_KEY_2;

-- IMPORTANT: paste public key body as a single uninterrupted base64 string
ALTER USER PIQLENS_APP_USER
SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxlRWpsHfpwikaGvldPe4LB/WGxAHczMGgHr4xElVNGYui6JZGdF2RCIy86wOvc+cHKUSDw2viZaBaOZJBVnAi7RkclxMQ+WeA9NxWflESFOtSze8ueRN59JyM+8Z7B/uqEw68U4BTUiOZAgBmkK//QToUlpWI9eOa53eRjZh1EaE+VXxC23+TRg9CmaOcx3eaCpJnSA/ytbepI6egWrVg7oFmu754z59PkVKibdl054abnVarScYHigC8qKFPOKbTXNSeOd7Udzf0Jx1h/7LZ6bmmfZNyTsSkdriGcx4CIZLInhSpjzbmuPZR4Uoj7zRL/nJ4a9UbU4s1y3ZKtKz4QIDAQAB
';

-- Primary verification
DESC USER PIQLENS_APP_USER;

-- Better parameter check syntax
SHOW PARAMETERS LIKE 'RSA_PUBLIC_KEY%' IN USER PIQLENS_APP_USER;

-- Additional user-level check
SHOW USERS LIKE 'PIQLENS_APP_USER';
ALTER USER PIQLENS_APP_USER
  SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxlRWpsHfpwikaGvldPe4LB/WGxAHczMGgHr4xElVNGYui6JZGdF2RCIy86wOvc+cHKUSDw2viZaBaOZJBVnAi7RkclxMQ+WeA9NxWflESFOtSze8ueRN59JyM+8Z7B/uqEw68U4BTUiOZAgBmkK//QToUlpWI9eOa53eRjZh1EaE+VXxC23+TRg9CmaOcx3eaCpJnSA/ytbepI6egWrVg7oFmu754z59PkVKibdl054abnVarScYHigC8qKFPOKbTXNSeOd7Udzf0Jx1h/7LZ6bmmfZNyTsSkdriGcx4CIZLInhSpjzbmuPZR4Uoj7zRL/nJ4a9UbU4s1y3ZKtKz4QIDAQAB
';
DESC USER PIQLENS_APP_USER;
SHOW PARAMETERS LIKE 'RSA_PUBLIC_KEY' FOR USER PIQLENS_APP_USER;
SHOW PARAMETERS LIKE 'RSA_PUBLIC_KEY_FP' FOR USER PIQLENS_APP_USER;
SHOW GRANTS TO USER PIQLENS_APP_USER;
SHOW GRANTS OF ROLE PIQLENS_ENGINEER_ROLE;

-- Runtime access validation must be executed while connected as PIQLENS_APP_USER
-- (or another user that actually has PIQLENS_ENGINEER_ROLE assigned).
-- If your worksheet user does not have PIQLENS_ENGINEER_ROLE, do not USE ROLE here.

-- Run the block below in a separate session authenticated as PIQLENS_APP_USER:
-- USE ROLE PIQLENS_ENGINEER_ROLE;
-- USE WAREHOUSE DQ_ANALYTICS_WH;
-- USE DATABASE DATA_QUALITY_DB;
-- USE SCHEMA DATA_CATALOG;
-- SELECT CURRENT_USER() AS USER_NAME,
--        CURRENT_ROLE() AS ACTIVE_ROLE,
--        CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE,
--        CURRENT_DATABASE() AS ACTIVE_DATABASE,
--        CURRENT_SCHEMA() AS ACTIVE_SCHEMA;

USE ROLE PIQLENS_ENGINEER_ROLE;
USE WAREHOUSE DQ_ANALYTICS_WH;
USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DATA_CATALOG;
SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();



DESC USER PIQLENS_APP_USER;
SELECT "property", "value"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "property" ILIKE 'RSA_PUBLIC_KEY%';
SHOW GRANTS TO USER PIQLENS_APP_USER;
SHOW GRANTS OF ROLE PIQLENS_ENGINEER_ROLE;




-- changing the role of the user 
GRANT ROLE PIQLENS_VIEWER_ROLE TO USER PIQLENS_APP_USER;
USE ROLE SECURITYADMIN;
ALTER USER PIQLENS_APP_USER
SET DEFAULT_ROLE = PIQLENS_VIEWER_ROLE;

GRANT ROLE PIQLENS_ADMIN_ROLE TO USER PIQLENS_APP_USER;
ALTER USER PIQLENS_APP_USER
SET DEFAULT_ROLE = PIQLENS_ADMIN_ROLE;
  -- choose desired role

describe user PIQLENS_APP_USER;

  SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();