-- ============================================================================
-- PI-QUALYTICS DATA QUALITY PLATFORM - PRODUCTION SCHEMA
-- ============================================================================
-- Purpose: Initialize Core Snowflake environment and Medallion Architecture
-- Removes all test/dummy inserts. Idempotent execution only.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- 1. WAREHOUSE SETUP
-- ============================================================================
CREATE WAREHOUSE IF NOT EXISTS DQ_INGESTION_WH WITH WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE IF NOT EXISTS DQ_ANALYTICS_WH WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

-- ============================================================================
-- 2. DQ FRAMEWORK DATABASE
-- ============================================================================
CREATE DATABASE IF NOT EXISTS DATA_QUALITY_DB DATA_RETENTION_TIME_IN_DAYS = 30;
USE DATABASE DATA_QUALITY_DB;

CREATE SCHEMA IF NOT EXISTS DQ_CONFIG;
CREATE SCHEMA IF NOT EXISTS DQ_METRICS;
CREATE SCHEMA IF NOT EXISTS DQ_ENGINE;

-- ============================================================================
-- 3. DQ_CONFIG TABLES (Metadata & Governance)
-- ============================================================================
USE SCHEMA DQ_CONFIG;

-- Governance: Data Ownership
CREATE TABLE IF NOT EXISTS DQ_DATASET_OWNERSHIP (
    OWNERSHIP_ID VARCHAR(36) DEFAULT UUID_STRING(),
    DATASET_NAME VARCHAR(200) NOT NULL,
    SCHEMA_NAME VARCHAR(100) NOT NULL,
    DATABASE_NAME VARCHAR(100) NOT NULL,
    DATA_OWNER VARCHAR(100),
    DATA_STEWARD VARCHAR(100),
    CRITICALITY VARCHAR(20),
    CONTACT_EMAIL VARCHAR(100),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, DATASET_NAME)
);

-- Governance: SLA Configuration
CREATE TABLE IF NOT EXISTS DQ_SLA_CONFIG (
    SLA_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    DATASET_NAME VARCHAR(200),
    SCHEMA_NAME VARCHAR(100),
    DATABASE_NAME VARCHAR(100),
    SLA_TYPE VARCHAR(50),
    THRESHOLD_VALUE VARCHAR(50),
    WINDOW_HOURS INT,
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100)
);

-- Governance: Policies
CREATE TABLE IF NOT EXISTS DQ_GOVERNANCE_POLICIES (
    POLICY_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    POLICY_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    SCOPE VARCHAR(100),
    IS_ENFORCED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Governance: Audit
CREATE TABLE IF NOT EXISTS DQ_GOVERNANCE_AUDIT (
    AUDIT_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID VARCHAR(36),
    ACTION VARCHAR(50),
    CHANGED_BY VARCHAR(100),
    CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    OLD_VALUE VARIANT,
    NEW_VALUE VARIANT
);

-- Quality: Master Rules
CREATE TABLE IF NOT EXISTS RULE_MASTER (
    RULE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RULE_NAME VARCHAR(100) NOT NULL UNIQUE,
    RULE_TYPE VARCHAR(50) NOT NULL,
    RULE_LEVEL VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(100),
    MODIFIED_TS TIMESTAMP_NTZ
);

-- Quality: Rule SQL Templates
CREATE TABLE IF NOT EXISTS RULE_SQL_TEMPLATE (
    TEMPLATE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RULE_ID NUMBER NOT NULL,
    SQL_TEMPLATE VARCHAR(4000) NOT NULL,
    TEMPLATE_VERSION NUMBER DEFAULT 1,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(100),
    MODIFIED_TS TIMESTAMP_NTZ,
    CONSTRAINT FK_TEMPLATE_RULE FOREIGN KEY (RULE_ID) REFERENCES RULE_MASTER(RULE_ID)
);

-- Quality: Dataset Linkage
CREATE TABLE IF NOT EXISTS DATASET_CONFIG (
    DATASET_ID VARCHAR(100) PRIMARY KEY,
    SOURCE_DATABASE VARCHAR(100) NOT NULL,
    SOURCE_SCHEMA VARCHAR(100) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    BUSINESS_DOMAIN VARCHAR(100),
    CRITICALITY VARCHAR(20) DEFAULT 'MEDIUM',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(100),
    MODIFIED_TS TIMESTAMP_NTZ,
    CONSTRAINT UK_DATASET UNIQUE (SOURCE_DATABASE, SOURCE_SCHEMA, SOURCE_TABLE)
);

CREATE TABLE IF NOT EXISTS DATASET_RULE_CONFIG (
    CONFIG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DATASET_ID VARCHAR(100) NOT NULL,
    RULE_ID NUMBER NOT NULL,
    COLUMN_NAME VARCHAR(100),
    THRESHOLD_VALUE NUMBER(10,2) DEFAULT 90.00,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(100),
    MODIFIED_TS TIMESTAMP_NTZ,
    CONSTRAINT FK_DRC_DATASET FOREIGN KEY (DATASET_ID) REFERENCES DATASET_CONFIG(DATASET_ID),
    CONSTRAINT FK_DRC_RULE FOREIGN KEY (RULE_ID) REFERENCES RULE_MASTER(RULE_ID),
    CONSTRAINT UK_DATASET_RULE_COLUMN UNIQUE (DATASET_ID, RULE_ID, COLUMN_NAME)
);

CREATE TABLE IF NOT EXISTS WEIGHTS_MAPPING (
    WEIGHT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RULE_TYPE VARCHAR(50) NOT NULL,
    BUSINESS_DOMAIN VARCHAR(100),
    WEIGHT NUMBER(5,2) DEFAULT 1.00,
    PRIORITY NUMBER DEFAULT 3,
    EFFECTIVE_DATE DATE DEFAULT CURRENT_DATE(),
    EXPIRY_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- 4. DQ_METRICS TABLES (Execution Logs & Results)
-- ============================================================================
USE SCHEMA DQ_METRICS;

CREATE TABLE IF NOT EXISTS DQ_RUN_CONTROL (
    RUN_ID VARCHAR(50) PRIMARY KEY,
    START_TS TIMESTAMP_NTZ,
    END_TS TIMESTAMP_NTZ,
    STATUS VARCHAR(20),
    TOTAL_CHECKS NUMBER,
    PASSED_CHECKS NUMBER,
    FAILED_CHECKS NUMBER,
    EXECUTION_MODE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS DQ_DAILY_SUMMARY (
    SUMMARY_ID VARCHAR(50) DEFAULT UUID_STRING() PRIMARY KEY,
    SUMMARY_DATE DATE NOT NULL,
    TABLE_NAME VARCHAR(200) NOT NULL,
    TOTAL_CHECKS NUMBER,
    PASSED_CHECKS NUMBER,
    FAILED_CHECKS NUMBER,
    DQ_SCORE NUMBER(5,2),
    LAST_RUN_ID VARCHAR(50),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Add clustered index by date for faster UI aggregation
ALTER TABLE DQ_DAILY_SUMMARY CLUSTER BY (SUMMARY_DATE);

CREATE TABLE IF NOT EXISTS DQ_CHECK_RESULTS (
    RESULT_ID VARCHAR(50) DEFAULT UUID_STRING() PRIMARY KEY,
    CHECK_ID VARCHAR(50),
    RUN_ID VARCHAR(50),
    TABLE_NAME VARCHAR(200) NOT NULL,
    COLUMN_NAME VARCHAR(100),
    CHECK_TYPE VARCHAR(50),
    CHECK_STATUS VARCHAR(20),
    EXPECTED_VALUE VARCHAR(500),
    ACTUAL_VALUE VARCHAR(500),
    SEVERITY VARCHAR(20),
    CHECK_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
ALTER TABLE DQ_CHECK_RESULTS CLUSTER BY (TABLE_NAME, CHECK_TIMESTAMP);

-- ============================================================================
-- 5. SECURE PERMISSIONS
-- ============================================================================
GRANT ALL ON DATABASE DATA_QUALITY_DB TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE DATA_QUALITY_DB TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA DQ_CONFIG TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA DQ_METRICS TO ROLE ACCOUNTADMIN;
